#!/bin/bash
# Grab zip from https://github.com/bmatzelle/gow and add to C:\Program Files\Git\usr\bin
echo "---PUBLISHING---"
zip -0 -r -q update.zip . &&
az webapp deployment source config-zip --resource-group "v-micricQuickTS" --name "v-micricQuickTS" --src "update.zip" --verbose --debug
rm -f update.zip